name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t my-app .  # Construire l'image Docker

      # Étape 3: Scanner l'image Docker avec Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-app"
          format: 'table'  # Scanner au format lisible (table)

      # Étape 4.1: Scanner l'image Docker avec Snyk (format table affiché)
      - name: Snyk test - Show table output
        continue-on-error: true
        uses: snyk/actions/docker@master
        with:
          image: my-app
          args: --file=Dockerfile --json-file-output=snyk-report.json # Normal test (table affichée dans les logs)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Étape 5: Détecter les secrets avec GitLeaks
      - name: Gitleaks check
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Étape 6: Upload du rapport JSON (optionnel mais conseillé)
      - name: Upload Snyk JSON report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json

      # Étape 7: Nettoyer l'image Docker
      - name: Clean up Docker image
        run: |
          docker rmi my-app
